# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-15 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_oauthqquser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthqquser',
            options={'verbose_name': 'Github用户数据', 'verbose_name_plural': 'Github用户数据'},
        ),
        migrations.AlterModelTable(
            name='oauthqquser',
            table='tb_oauth_github',
        ),
    ]
